### ISSUE TITLE
V2: Update tests to check new behaviour and abilities

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#813]
A lot of the legacy tests are checking against internal state and values, instead all the tests must be checking against the API or values directly.

Every test is in a separate file, with groups of tests having a module defining them. All tests must complete before the next test is allowed to start.

### 1. Core
- [x] Arguments
  - [x] Overload variation #&#xfeff;1a: Velocity(ELEMENT, {properties})
  - [x] Overload variation #&#xfeff;1b: Velocity(element, {PROPERTIES})
  - [x] Overload variation #&#xfeff;2a: Velocity(element, {properties}, DURATION<number>)
  - [x] Overload variation #&#xfeff;2b: Velocity(element, {properties}, DURATION<slow>)
  - [x] Overload variation #&#xfeff;2c: Velocity(element, {properties}, DURATION<normal>)
  - [x] Overload variation #&#xfeff;2d: Velocity(element, {properties}, DURATION<fast>)
  - [x] Overload variation #&#xfeff;3: Velocity(element, {properties}, EASING)
  - [x] Overload variation #&#xfeff;4: Velocity(element, {properties}, COMPLETE)
  - [x] Overload variation #&#xfeff;5a: Velocity(element, {properties}, DURATION, easing)
  - [x] Overload variation #&#xfeff;5b: Velocity(element, {properties}, duration, EASING)
  - [x] Overload variation #&#xfeff;6a: Velocity(element, {properties}, DURATION, complete)
  - [x] Overload variation #&#xfeff;6b: Velocity(element, {properties}, duration, COMPLETE)
  - [x] Overload variation #&#xfeff;7a: Velocity(element, {properties}, DURATION, easing, complete)
  - [x] Overload variation #&#xfeff;7b: Velocity(element, {properties}, duration, EASING, complete)
  - [x] Overload variation #&#xfeff;7c: Velocity(element, {properties}, duration, easing, COMPLETE)
  - [x] Overload variation #&#xfeff;8: Velocity(element, {properties}, {OPTIONS})
  - [x] Overload variation #&#xfeff;9: Velocity({elements:[elements], properties:{properties}, options:{OPTIONS})
  - [x] Overload variation #&#xfeff;10: Velocity({elements:[elements], properties:\"ACTION\", options:{OPTIONS})
- [x] End Value Caching
  - [x] Stale end value #1 wasn't pulled.@ 385 ms
  - [x] Stale end value #2 wasn't pulled.@ 385 ms
  - [x] Chained end value #1 was pulled.@ 784 ms
  - [x] Chained end value #2 was pulled.
- [x] End Value Setting
  - [x] Standard end value #1 was set.@ 386 ms
  - [x] Standard end value #2 was set.
- [ ] Start Value Calculation

### 2. Options
- [x] Option: **Begin**
  - [x] Elements passed into callback.
- [x] Option: **Complete**
  - [x] Elements passed into callback.
- [x] Option: **Delay**
  - [x] Delayed calls start after the correct delay.
  - [x] Queued delays start after the correct delay.
- [x] Option: **Easing**
  - [x] Fake easing string didn't throw error.
  - [x] Invalid bezier curve didn't throw error.
  - [x] Array converted into bezier function.
  - [x] Array with duration converted into springRK4 function.
  - [ ] Array without duration converted into springRK4 duration.
  - [x] Array converted into Step function.
  - [x] Correct begin value (easing:'at-start').
  - [x] Correct progress value (easing:'at-start').
  - [x] Correct complete value (easing:'at-start').
  - [x] Correct begin value (easing:'during').
  - [x] Correct progress value (easing:'during').
  - [x] Correct complete value (easing:'during').
  - [x] Correct begin value (easing:'at-end').
  - [x] Correct progress value (easing:'at-end').
  - [x] Correct complete value (easing:'at-end').
- [x] Option: **FPS Limit**
  - [x] Setting global fps limit to 5
  - [x] ...counted ? frames (±1 frame)
  - [x] Setting global fps limit to 15
  - [x] ...counted ? frames (±1 frame)
  - [x] Setting global fps limit to 30
  - [x] ...counted ? frames (±1 frame)
  - [x] Setting global fps limit to 60
  - [x] ...counted ? frames (±1 frame)
- [x] Option: **Loop**
  - [x] Begin callback only called once.
  - [x] Animation looped correct number of times (once each direction per loop).
  - [x] Looping with 'delay' is correct.
  - [x] Complete callback only called once.
- [x] Option: **Progress**
  - [x] Elements passed into progress.
  - [x] Elements passed into progress as this.
  - [x] 'percentComplete' passed into progress.
  - [x] 'msRemaining' passed into progress.
- [x] Option: **Queue**
  - [x] Custom queue is empty.
  - [x] Queued animation isn't started early.
  - [x] Custom queue was created.
  - [x] Queued animation starts after first.
  - [x] Custom queue grows.
  - [x] Different queue animation starts in parallel.
  - [x] Queue:false animation starts in parallel.
- [x] Option: **Repeat**
  - [x] Begin callback only called once.
  - [x] Animation repeated correct number of times (original plus repeats).
  - [x] Repeat with 'delay' has correct duration.
  - [x] Complete callback only called once.
- [x] Option: **Speed**
  - [x] Speed on options overrides default.
  - [x] Velocity.defaults.speed change is respected. (×3, ?ms ±32ms)
  - [x] Double speed animation lasts half as long. (×2, ?ms ±32ms)
  - [x] Delayed animation includes speed for delay. (×2, ?ms ±32ms)
  - [x] Negative delay animation includes speed for delay. (×2, ?ms ±32ms)
  - [x] Half speed animation lasts twice as long. (×½, ?ms ±64ms)
  - [x] Frozen (speed:0) animation doesn't progress.

### 3. Command
- [x] Command: **Finish**
  - [x] Calling on an element that isn't animating doesn't cause an error.
  - [x] Calling on an element that is animating doesn't cause an error.
  - [x] Finish once starts the second animation.
  - [x] Finish twice starts the third animation.
  - [x] Finish 'true' finishes all animations.
  - [x] Finish animation with correct queue.
  - [x] Don't finish animation with wrong queue.
  - [x] Finish calls 'begin()' callback without delay.
  - [x] Finish calls 'complete()' callback without delay.
  - [x] Finish animation with correct value.
  - [x] Finish calls 'begin()' callback with delay.
  - [x] Finish calls 'complete()' callback with delay.
  - [x] Finish animation with correct value before delay ends.
- [x] Command: **Pause + Resume**
  - [x] Property value unchanged after pause.
  - [x] Property value unchanged after pause during delay.
  - [x] Delayed tween did not start early after pause.
  - [x] Tween completed after pause/resume.
  - [x] Delayed tween completed after pause/resume.
  - [x] Tween value and percentageComplete correlate correctly after pause.
  - [x] Second tween animation must have not started when pausing both elements and resuming first tween.
  - [x] First tween animation must be completed when pausing both elements and resuming only first tween.
  - [x] Second tween animation must have not started when pausing both elements and resuming first tween when in same queue.
  - [x] First tween animation must be completed when pausing both elements and resuming only first tween when in same queue.
  - [x] Animation with {queue:false} will run regardless of previously paused animations.
  - [x] Queued animation began after previously paused animation completed
- [ ] Command PauseAll + ResumeAll
- [ ] Command Reverse
- [ ] ~~Command Scroll~~
- [x] Command: **Stop**
  - [x] Calling on an element that isn't animating doesn't cause an error.
  - [x] Calling on an element that is animating doesn't cause an error.
  - [x] Animation runs until stopped.
  - [x] Stop animation before delay ends.
  - [x] Stop animation with correct queue.
  - [x] Don't stop animation with wrong queue.
  - [x] Stop 'true' stops all animations.
  - [x] Stop without arguments on a chain stops chain animations.
  - [x] Stop without arguments on a chain doesn't stop other animations.
- [x] Command: **Tween**
  - [x] Invalid percentComplete throws an error.
  - [x] Passing more than one target throws an error.
  - [x] Invalid propertyMap throws an error.
  - [x] Property without an element must be forcefed or throw an error.
  - [x] Calling on an chain returns the correct value.
  - [x] Calling with an element returns the correct value.
  - [x] Calling without an element returns the correct value.
  - [x] Ensure that the element is not altered.
  - [x] Calling a single property returns a value.
  - [x] Calling a propertiesMap returns an object.
  - [x] Calling directly returns the same as a chain.

### 4. Feature
- [x] Feature: **'velocity-animating' Classname**
  - [x] Class added.
  - [x] Class removed.
- [ ] Feature Colors
- [ ] Feature Forcefeeding
- [x] Feature: **Promises**
  - [x] Calling with no arguments should reject a Promise.
  - [x] Calling with no properties should reject a Promise.
  - [x] Stop call fulfilled after correct delay.
  - [x] Calling with empty properties + duration should not reject a Promise.
  - [x] Calling with a single element fulfills with a single element array.
  - [x] Calling with multiple elements fulfills with a multiple element array.
  - [x] Calling with empty properties should not reject a Promise.
  - [x] Calling with invalid arguments should reject a Promise.
  - [x] Queued call fulfilled after correct delay.
- [ ] Feature Redirects
- [ ] Feature Value Functions

### 5. UI Pack
* The code from this has been merged, so this should either test the packaged effects, or be renamed and changed to test the new form of sequences.
- [ ] Packaged Effect slideUp+Down
- [ ] UI Pack Call Options
- [ ] UI Pack Callbacks
- [ ] UI Pack In+Out
- [ ] UI Pack RegisterEffect
- [ ] UI Pack RunSequence

### 6. Properties
- [x] Properties: **Display**
  - [x] Display:'block' was set immediately.
  - [x] Display:'auto' was understood.
  - [x] Display:'auto' was cached as 'block'.
  - [x] Display:'' was reset correctly.
  - [x] Display:'none' was not set immediately.
  - [x] Display:'none' was set upon completion.
- [ ] Properties: **Scroll**
- [x] Properties: **Visibility**
  - [x] Visibility:'visible' was set immediately.
  - [x] Visibility:'' was reset correctly.
  - [x] Visibility:'hidden' was not set immediately.
  - [x] Visibility:'hidden' was set upon completion.

**Comment by Rycochet** [comment]
Closing due to #927

All tests need to be rewritten as Unit Tests
